AUGMENTATION: True
IMAGE_SIZE: [224,224,3] # as per VGG 16 model
BATCH_SIZE: 20
INCLUDE_TOP: False
EPOCHS: 20 #should be 200 - 300 to inspect model performance
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.0001